import sys
import os
import io

# Add the path of ai_features to sys.path
current_dir = os.path.dirname(os.path.abspath(__file__))
ai_features_path = os.path.abspath(os.path.join(current_dir))
if ai_features_path not in sys.path:
    sys.path.append(ai_features_path)

from google import genai
from google.genai import types
import PIL.Image
import os
import dotenv
from prompts_config import SYSTEM_PROMPTS
import json

dotenv.load_dotenv()

# 1. Initialize the Client with your API Key
client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

def analyze_pet_photo(photo_path, prompt_key):
    image = PIL.Image.open(photo_path)
    system_instruction = SYSTEM_PROMPTS[prompt_key]
    response = client.models.generate_content(
        model="gemini-2.0-flash",
        contents=[image, system_instruction],
        config=types.GenerateContentConfig(system_instruction=system_instruction)
    )
    return response.text

def analyze_pet_poop(poop_photo_path):
    result = analyze_pet_photo(poop_photo_path, "poop_analysis")
    return result

def format_json(result):
    try:
        result = clean_json(result)
        data = json.loads(result)
        return data
    except json.JSONDecodeError:
        result = reformat_json(result)
        try:
            data = json.loads(result)
            return data
        except json.JSONDecodeError:
            return None
    return None

def clean_json(result):
    return result.replace("```json", "").replace("```", "")

def reformat_json(result):
    """Use Gemini to fix malformed JSON so it can be parsed by json.loads()."""
    response = client.models.generate_content(
        model="gemini-2.0-flash",
        contents=[result],
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPTS["reformat_json"]
        )
    )
    repaired = clean_json(response.text)
    return repaired

def process_message(message):
    """Use Gemini to process user message and generate response"""
    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash-lite",
            contents=[message],
            config=types.GenerateContentConfig(
                system_instruction=SYSTEM_PROMPTS["process_message"]
            )
        ).text
    except Exception as e:
        response = str(e)

    return response

def process_message(message):
    """Use Gemini to process user uploaded image and generate response"""
    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash-lite",
            contents=[message],
            config=types.GenerateContentConfig(
                system_instruction=SYSTEM_PROMPTS["process_message"]
            )
        ).text
    except Exception as e:
        response = str(e)

    return response

def process_image(image_parts):
    """
    Use Gemini to process user-uploaded image and generate a response.

    Args:
        image_parts (dict): Metadata & content of the image

    Returns:
        str: The response generated by the Gemini model.
    """
    return "TODO: Complete the request to upload image to gemini"
    try:
        # Generate content using Gemini
        response = client.models.generate_content(
            model="gemini-2.5-flash-lite",
            contents=[image_parts],
            config=types.GenerateContentConfig(
                system_instruction=SYSTEM_PROMPTS["process_image"]
            )
        )
        return response.text
    except Exception as e:
        return str(e)

# def main():
#     poop_photo_path = "assets/images/pet_poop.jpg"
#     result = analyze_pet_poop(poop_photo_path)
#     formatted_result = format_json(result)
#     print(formatted_result)

# if __name__ == "__main__":
#     main()